apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: egress-gw
  namespace: flux
spec:
  interval: 10m0s
  path: ./manifests/egress-gw
  prune: true
  sourceRef:
    kind: GitRepository
    name: labs
  postBuild:
    substitute:
      destination_cidr: "172.18.0.0/16"
      egress_ip: "172.18.0.5"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: lb-controller
  namespace: flux
spec:
  interval: 10m0s
  path: ./manifests/metallb-l2
  prune: true
  sourceRef:
    kind: GitRepository
    name: labs
