---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux
spec:
  interval: 10m0s
  path: ./manifests/gateway-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: labs
