apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-controller
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.0.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux
      interval: 1m
  values:
    admissionWebhooks:
      enabled: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: lb-controller
  namespace: flux
spec:
  interval: 10m0s
  path: ./manifests/metallb-l2
  prune: true
  sourceRef:
    kind: GitRepository
    name: labs
