kind: ConfigMap
apiVersion: v1
metadata:
  name: metallb
  namespace: kube-system
data:
  config: |
    address-pools:
    - addresses:
      - 198.51.100.0/24
      name: default
      protocol: layer2
